Rule1 = begin [optional things] end.
Rule2 = begin {and again} end.
Rule3 = I am a (good | bad) programmer.
Linebreak = First line \n Second line \n End.
Optimize1 = ab {ab}.
Optimize2 = ab { cd ab}.
Quote = "'" a "'".